### ISSUE TITLE
feat: 关于后端地址填写的改进意见

### ISSUE THREAD

**Issue by Well2333** [wosiwq/nonebot-plugin-bilichat-webui#1]
ref https://github.com/Well2333/nonebot-plugin-bilichat/issues/150

在填写后端地址时，WebUI会在路径中无条件添加 `/api/`，导致URL出现错误
![image](https://github.com/wosiwq/nonebot-plugin-bilichat-webui/assets/40534114/3e3e1681-6c33-4fe8-ab7b-127e0e71bea7)

1. 对于为后端采用 nginx 等工具进行反向代理的用户，其 `/api` 路径也可能一并添加到链接转换中，因此个人认为不应将 `/api` 在前端重复添加，而应该认为其已经包含在后端中。
2. 输入URL后应检测用户输入的字符串是否以 `/` 结尾，否则将可能出现如图的错误
3. 输入URL后应检查 api 是否能正常访问，对无法正常访问的情况应进行 **明显** 的提示

**Comment by wosiwq** [comment]
反代用户应能清晰的认知到反代后的结果是什么 url校验在路上了 周一搞

**Comment by wosiwq** [comment]
fix with: cbadb78a96dd3be4645370e1a7ba732d9ae925ef
