### ISSUE TITLE
feat: 优化配置文件可视化的显示样式

### ISSUE THREAD

**Issue by Well2333** [wosiwq/nonebot-plugin-bilichat-webui#2]
![image](https://github.com/wosiwq/nonebot-plugin-bilichat-webui/assets/40534114/b546c2d6-f26c-4180-8967-afd41a738600)

1. 隐藏 uploader 列表（因为 uploader 列表无需用户改动）
2. 替换订阅配置中展示的up uid 为 up 昵称

在上传配置后，如果用户的订阅列表中出现了新的 up，后端会自动将此up添加至列表中，所以前端无需展示和处理此部分配置

**Comment by wosiwq** [comment]
订阅配置内的uid能否保证一定在uploader的list内

**Comment by Well2333** [comment]
> 订阅配置内的uid能否保证一定在uploader的list内

上传至服务端的无需保证（甚至可以传空list），由服务端返回的一定可以保证

**Comment by wosiwq** [comment]
fix in : 0807eb372d1e20f124a7b547c6c78a550a9015ee
